// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'rx_workers_test.dart' as rx_workers_test;

void main() {
  rx_workers_test.main();
}
