// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'get_instance_test.dart' as get_instance_test;

void main() {
  get_instance_test.main();
}
